# Generated by Django 3.2.4 on 2021-06-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MemberVO',
            fields=[
                ('username', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=10)),
                ('name', models.TextField()),
                ('email', models.EmailField(max_length=254)),
            ],
            options={
                'db_table': 'members',
                'managed': True,
            },
        ),
    ]
